# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b1b1558ffd0369038a47d5959218659ef412fdd844704399e50850cdf796a09e3fe3e9081e9a577415ff47b4047da63666faedf0f73677ae10204e80b5841f2

test:
  secret_key_base: 02deda10bba46375300a87f2554ccbc4cfa186b18b8d89914649ea505c0813e89eed29e6a249d5c927c146fc47ddff646d58d176c07ad54129e11ed0a5e8af89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
